# Enable deep sleep after 60 min of inactivity
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

# Increase BLE TX power to reduce peripheral latency
CONFIG_BT_CTLR_TX_PWR_PLUS_3=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Battery reporting every 15 minutes
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=900

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable mouse/pointer emulation
CONFIG_ZMK_POINTING=y

# Enable layer report module (sends active layer bitmask over HID)
CONFIG_ZMK_LAYER_REPORT=y

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y
